apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: netflix
  name: netflix
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: netflix
  type: NodePort
status:
  loadBalancer: {}
